apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  labels:
    app: cp
  name: cp
  selfLink: /apis/apps.openshift.io/v1/namespaces/insights-qe-dev/deploymentconfigs/cp
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: cp
    deploymentconfig: cp
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: cp
        deploymentconfig: cp
    spec:
      containers:
      - env:
        - name: SSH_KEY
          value: '-----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----'
        image: quay.io/ecerquei/util@sha256:e19140ebe9f4980e2758875631604a46525ed59ef3ff5ad1a4c8ff8dc3617637
        imagePullPolicy: Always
        name: cp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - cp
      from:
        kind: ImageStreamTag
        name: cp:latest
        namespace: insights-qe-dev
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
