apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  labels:
    app: sshfs
  name: sshfs
  selfLink: /apis/apps.openshift.io/v1/namespaces/insights-qe-dev/deploymentconfigs/cp
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: sshfs
    deploymentconfig: sshfs
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: sshfs
        deploymentconfig: sshfs
    spec:
      containers:
      - env:
        - name: SSH_KEY
          value: '-----BEGIN RSA PRIVATE KEY----- 
            -----END RSA PRIVATE KEY-----'
        image: quay.io/ecerquei/util:latest
        imagePullPolicy: Always
        name: sshfs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sshfs
      from:
        kind: ImageStreamTag
        name: quay.io/ecerquei/sshfs:latest
        namespace: insights-qe-dev
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
